homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Radio Google Version 1.0'
        author: 'Salvatore Lentini'
        reference: ' WebSite: www.domhouse.it - telegram @theturiddu'

input_select:
  stazioni_radio:
    name: 'Seleziona Stazione Radio:'
    options:
      - M2O
      - RADIO EMOTIONS
      - DISCORADIO
      - RADIO DEEJAY
      - RTL
      - KISS KISS
      - RADIO CAPITAL
      - VIRGIN RADIO
      - RMC
      - RDS
      - RADIO ZETA
      - DANCE FLOOR ANNI NOVANTA
    initial: M2O
    icon: mdi:play

  stazioni_loghi:
    options:
      - i.ibb.co/LJwWp6D/M2o-logo.png #M20 
      - i.ibb.co/D4c5PtJ/Radio-Emotions-Logo.jpg # RADIO-EMOTIONS
      - i.ibb.co/rkxQDHL/DISCORADIOLOGO.jpg #DISCORADIO
      - i.ibb.co/dmW11GK/Radio-Deejay-Logo.png #RADIO DEEJAY
      - i.ibb.co/z2fQdK7/RTL-Logo.png # RTL
      - i.ibb.co/PFKCw5r/KISS-KISS-LOGO.png #KISS-KISS
      - i.ibb.co/F0pbjxg/RADIO-CAPITAL-LOGO.png #RADIO-CAPITAL
      - i.ibb.co/gy88Wsd/VIRGIN-RADIO-LOGO.png #VIRGIN RADIO
      - i.ibb.co/bQ2nQwh/RADIO-MONTE-CARLO-LOGO.png # RADIO-MONTE-CARLO
      - i.ibb.co/2Mv6Ggy/RDS-LOGO.png #RDS
      - i.ibb.co/fCvC9Z4/RADIO-ZETA-LOGO.png #RADIO-Z
      - i.ibb.co/VLzqzwh/DANCE-FLOR-ANNI90.png # DANCE FLOOR ANNI 90
    initial: i.ibb.co/LJwWp6D/M2o-logo.png
    
  google_speaker:
    name: Google Speaker # inserire i media player  esempio media_player.salotto dovrà essere inserito solo salotto
    options:
      - "salotto"
      - "studio"
      - "camera"
      - "cucina"
      - "cucina_salotto"
      - "google_home_tutti"
    initial: "cucina_salotto"  # media player di default
    icon: mdi:google-home  

script:
 radio:
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.{{ states('input_select.google_speaker') }}
          volume_level: '0.65' # volume impostato quando la radio va in on
      - service: media_player.play_media
        data_template:
          entity_id: media_player.{{ states('input_select.google_speaker') }}
          media_content_id: >
            {% if is_state("input_select.stazioni_radio", "M2O") %} http://radiom2o-lh.akamaihd.net/i/RadioM2o_Live_1@42518/master.m3u8
            {% elif is_state("input_select.stazioni_radio", "RADIO EMOTIONS") %} http://icecast.dns-lab.it:8116/;stream.mp3
            {% elif is_state("input_select.stazioni_radio", "DISCORADIO") %} http://icstream.rds.radio/disco
            {% elif is_state("input_select.stazioni_radio", "RADIO DEEJAY") %} http://radiodeejay-lh.akamaihd.net/i/RadioDeejay_Live_1@189857/master.m3u8
            {% elif is_state("input_select.stazioni_radio", "RTL") %} http://streamingv2.shoutcast.com/rtl-1025
            {% elif is_state("input_select.stazioni_radio", "KISS KISS") %} http://wma08.fluidstream.net:8080/KissKiss.mp3
            {% elif is_state("input_select.stazioni_radio", "RADIO CAPITAL") %} http://radiocapital-lh.akamaihd.net/i/RadioCapital_Live_1@196312/master.m3u8
            {% elif is_state("input_select.stazioni_radio", "VIRGIN RADIO") %} http://icecast.unitedradio.it/Virgin.mp3
            {% elif is_state("input_select.stazioni_radio", "RMC") %} http://edge.radiomontecarlo.net/RMC.mp3
            {% elif is_state("input_select.stazioni_radio", "RDS") %} http://stream1.rds.it:8000/rds64k
            {% elif is_state("input_select.stazioni_radio", "RADIO ZETA") %} http://shoutcast.rtl.it:3030/stream/1/
            {% elif is_state("input_select.stazioni_radio", "DANCE FLOOR ANNI NOVANTA") %} http://185.92.223.206:443/live-aac
            {% endif %}
          media_content_type: music
          
 stop_radio:
    sequence:
      - service: media_player.media_stop
        data_template:
          entity_id: media_player.{{ states('input_select.google_speaker') }}
      - delay: '1'          
      - service: media_player.volume_set
        data:
          entity_id: media_player.{{ states('input_select.google_speaker') }}
          volume_level: '1'  #  riporta il volume di google al massimo quando la radio va in off
      - delay: '1'         
      - service: media_player.turn_off
        data_template:
          entity_id: media_player.{{ states('input_select.google_speaker') }}
camera:      
  - platform: generic
    name: logo-stazione
    still_image_url: https://{{ states('input_select.stazioni_loghi') }}
          
automation:   
- alias: M2O LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: M2O
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/LJwWp6D/M2o-logo.png

- alias: RADIO-EMOTIONS LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: RADIO EMOTIONS
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/D4c5PtJ/Radio-Emotions-Logo.jpg

- alias: DISCORADIO LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: DISCORADIO
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/rkxQDHL/DISCORADIOLOGO.jpg
          
- alias: RADIO DEEJAY LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: RADIO DEEJAY
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/dmW11GK/Radio-Deejay-Logo.png
          
- alias: RTL LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: RTL
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/z2fQdK7/RTL-Logo.png
          
- alias: KISS KISS LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: KISS KISS
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/PFKCw5r/KISS-KISS-LOGO.png
          
- alias: RADIO CAPITAL LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: RADIO CAPITAL
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/F0pbjxg/RADIO-CAPITAL-LOGO.png
          
- alias: VIRGIN RADIO LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: VIRGIN RADIO
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/gy88Wsd/VIRGIN-RADIO-LOGO.png
          
- alias: RMC LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: RMC
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/bQ2nQwh/RADIO-MONTE-CARLO-LOGO.png
          
- alias: RDS LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: RDS
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/2Mv6Ggy/RDS-LOGO.png
          
- alias: RADIO ZETA LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: RADIO ZETA
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/fCvC9Z4/RADIO-ZETA-LOGO.png
          
- alias: RADIO DANCE FLOOR ANNI NOVANTA LOGO
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.stazioni_radio
    to: DANCE FLOOR ANNI NOVANTA
  condition: []
  action:
      - service: input_select.select_option
        data:
          entity_id: input_select.stazioni_loghi
          option: i.ibb.co/VLzqzwh/DANCE-FLOR-ANNI90.png
          